
"""

"""
from pandas import (
    ArrowDtype,
    BooleanDtype,
    Categorical,
    CategoricalDtype,
    CategoricalIndex,
    DataFrame,
    DateOffset,
    DatetimeIndex,
    DatetimeTZDtype,
    # ExcelFile,
    # ExcelWriter,
    Flags,
    Float32Dtype,
    Float64Dtype,
    Grouper,
    HDFStore,
    Index,
    IndexSlice,
    Int16Dtype,
    Int32Dtype,
    Int64Dtype,
    Int8Dtype,
    Interval,
    IntervalDtype,
    IntervalIndex,
    MultiIndex,
    NA,
    NaT,
    NamedAgg,
    Period,
    PeriodDtype,
    PeriodIndex,
    RangeIndex,
    Series,
    SparseDtype,
    StringDtype,
    Timedelta,
    TimedeltaIndex,
    Timestamp,
    UInt16Dtype,
    UInt32Dtype,
    UInt64Dtype,
    UInt8Dtype,
    api,
    array,
    arrays,
    bdate_range,
    concat,
    crosstab,
    cut,
    date_range,
    describe_option,
    errors,
    eval,
    factorize,
    get_dummies,
    from_dummies,
    get_option,
    infer_freq,
    interval_range,
    # io,
    isna,
    isnull,
    json_normalize,
    lreshape,
    melt,
    merge,
    merge_asof,
    merge_ordered,
    notna,
    notnull,
    offsets,
    option_context,
    options,
    period_range,
    pivot,
    pivot_table,
    plotting,
    qcut,
    # read_clipboard,
    # read_csv,
    # read_excel,
    # read_feather,
    # read_fwf,
    # read_gbq,
    # read_hdf,
    # read_html,
    # read_json,
    # read_orc,
    # read_parquet,
    # read_pickle,
    # read_sas,
    # read_spss,
    # read_sql,
    read_sql_query,
    # read_sql_table,
    # read_stata,
    # read_table,
    # read_xml,
    reset_option,
    set_eng_float_format,
    set_option,
    show_versions,
    test,
    testing,
    timedelta_range,
    to_datetime,
    to_numeric,
    # to_pickle,
    to_timedelta,
    tseries,
    unique,
    value_counts,
    wide_to_long,
)

__all__ = [
    'get_sql_result_to_df',
    'ArrowDtype',
    'BooleanDtype',
    'Categorical',
    'CategoricalDtype',
    'CategoricalIndex',
    'DataFrame',
    'DateOffset',
    'DatetimeIndex',
    'DatetimeTZDtype',
    # 'ExcelFile',
    # 'ExcelWriter',
    'Flags',
    'Float32Dtype',
    'Float64Dtype',
    'Grouper',
    'HDFStore',
    'Index',
    'IndexSlice',
    'Int16Dtype',
    'Int32Dtype',
    'Int64Dtype',
    'Int8Dtype',
    'Interval',
    'IntervalDtype',
    'IntervalIndex',
    'MultiIndex',
    'NA',
    'NaT',
    'NamedAgg',
    'Period',
    'PeriodDtype',
    'PeriodIndex',
    'RangeIndex',
    'Series',
    'SparseDtype',
    'StringDtype',
    'Timedelta',
    'TimedeltaIndex',
    'Timestamp',
    'UInt16Dtype',
    'UInt32Dtype',
    'UInt64Dtype',
    'UInt8Dtype',
    'api',
    'array',
    'arrays',
    'bdate_range',
    'concat',
    'crosstab',
    'cut',
    'date_range',
    'describe_option',
    'errors',
    'eval',
    'factorize',
    'get_dummies',
    'from_dummies',
    'get_option',
    'infer_freq',
    'interval_range',
    # 'io',
    'isna',
    'isnull',
    'json_normalize',
    'lreshape',
    'melt',
    'merge',
    'merge_asof',
    'merge_ordered',
    'notna',
    'notnull',
    'offsets',
    'option_context',
    'options',
    'period_range',
    'pivot',
    'pivot_table',
    'plotting',
    'qcut',
    # 'read_clipboard',
    # 'read_csv',
    # 'read_excel',
    # 'read_feather',
    # 'read_fwf',
    # 'read_gbq',
    # 'read_hdf',
    # 'read_html',
    # 'read_json',
    # 'read_orc',
    # 'read_parquet',
    # 'read_pickle',
    # 'read_sas',
    # 'read_spss',
    # 'read_sql',
    # 'read_sql_query',
    # 'read_sql_table',
    # 'read_stata',
    # 'read_table',
    # 'read_xml',
    'reset_option',
    'set_eng_float_format',
    'set_option',
    'show_versions',
    'test',
    'testing',
    'timedelta_range',
    'to_datetime',
    'to_numeric',
    # 'to_pickle',
    'to_timedelta',
    'tseries',
    'unique',
    'value_counts',
    'wide_to_long',
]

def get_sql_result_to_df(**kwargs):
    """
    Реинкарнация функции pandas.read_sql_query()
    !!! Читать документацию по pandas.
    """
    return read_sql_query(**kwargs)

